[package]
name = "algorithm"
version = "0.1.0"
authors = ["TheLudlows <ai-l@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simd = "0.2.4"