[package]
name = "common"
version = "0.1.0"
authors = ["liuchao56 <liuchao56@jd.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compressed_vec = "0.1.0"